
CREATE TABLE ROL(
ID_ROL INT PRIMARY KEY IDENTITY,
NOMBRE NVARCHAR(50),
FECHA_REGISTRO DATETIME DEFAULT GETDATE()
);
GO

INSERT INTO ROL (NOMBRE) VALUES ('Administrador');
INSERT INTO ROL (NOMBRE) VALUES('Empleado');
GO

CREATE PROC PA_LISTAR_ROLES
AS
BEGIN
SELECT * FROM ROL;
END;
GO

CREATE TABLE MENU(
ID_MENU INT PRIMARY KEY IDENTITY,
NOMBRE NVARCHAR(100),
URL_MENU NVARCHAR(100),
FECHA_REGISTRO DATETIME DEFAULT GETDATE()
);
GO

INSERT INTO MENU(NOMBRE, URL_MENU) VALUES 
('Usuario', '\Usuario' ), ('Autor', '\Autor' ), 
('Cliente', '\Cliente' ),('Libro', '\Libro' ),
('Genero', '\Genero' ),('Prestamo', '\Prestamo' );
GO

CREATE PROC PA_LISTAR_MENU
AS
BEGIN
SELECT * FROM MENU;
END;
GO

CREATE TABLE PERMISO(
ID_PERMISO INT PRIMARY KEY IDENTITY, 
ID_ROL INT REFERENCES ROL(ID_ROL),
ID_MENU INT REFERENCES MENU(ID_MENU)
);
GO

INSERT INTO PERMISO(ID_ROL, ID_MENU) VALUES (1,1),(1,2),(1,3),(1,4),(1,5),(1,6), (2,3), (2,4), (2,6);

CREATE TABLE USUARIO (
ID_USUARIO INT PRIMARY KEY IDENTITY,
USUARIO NVARCHAR(100),
CORREO NVARCHAR (100), 
CLAVE NVARCHAR(300),
ID_ROL INT REFERENCES ROL(ID_ROL),
ESTADO BIT, 
FECHA_REGISTRO DATETIME DEFAULT GETDATE()
);
GO

SELECT * FROM USUARIO;
INSERT INTO USUARIO (USUARIO, CORREO, CLAVE, ID_ROL, ESTADO) VALUES ('admin', 'admin@biblioteca.com', '12345', 1, 1);
INSERT INTO USUARIO (USUARIO, CORREO, CLAVE, ID_ROL, ESTADO) VALUES ('juanp', 'juanperez@biblioteca.com', 'abcde', 2, 1);
INSERT INTO USUARIO (USUARIO, CORREO, CLAVE, ID_ROL, ESTADO) VALUES ('mariaq', 'mariaquintero@biblioteca.com', 'clave123', 2, 1);
GO

CREATE PROC PA_LISTAR_USUARIOS
AS
BEGIN
SELECT * FROM USUARIO;
END;

GO
EXECUTE PA_LISTAR_USUARIOS;
GO

CREATE PROC PA_BUSCAR_NOMBRE_USUARIO(
 @usuario nvarchar(50)
 )
 AS
 BEGIN
    SELECT * FROM USUARIO WHERE USUARIO = @usuario
 END;
 GO

 CREATE PROCEDURE PA_BUSCAR_USUARIO_ID(
@id_usuario int
)
AS
BEGIN
SELECT * FROM USUARIO WHERE ID_USUARIO = @id_usuario;
END;


 EXECUTE PA_BUSCAR_NOMBRE_USUARIO
 @nombres = 'Sapo';
 GO

 CREATE PROC PA_INICIAR_SESION(
 @usuario nvarchar(100),
 @clave nvarchar(300)
 )
 AS
 BEGIN 
 SELECT U.ID_USUARIO, U.USUARIO, U.CORREO, U.CLAVE, R.ID_ROL, R.NOMBRE AS NOMBRE_ROL, U.ESTADO, U.FECHA_REGISTRO FROM USUARIO U 
 INNER JOIN ROL R ON U.ID_ROL = R.ID_ROL 
 WHERE USUARIO = @usuario AND CLAVE = @clave AND ESTADO = 1;  
 END;
GO


 CREATE PROC PA_REGISTRAR_USUARIO(
 @usuario nvarchar(100),
 @correo varchar(100),
 @clave nvarchar(300),
 @id_rol int,
 @estado bit
 )
 AS
 BEGIN
   INSERT INTO USUARIO (USUARIO, CORREO, CLAVE, ID_ROL, ESTADO) 
   VALUES (@usuario, @correo, @clave, @id_rol, @estado)
 END;
 GO
 
CREATE PROC PA_EDITAR_USUARIO(
@id_usuario int,
@usuario nvarchar(100),
@correo varchar(100),
@clave nvarchar(300),
@id_rol int,
@estado bit
)
AS
BEGIN
	UPDATE USUARIO SET USUARIO = @usuario ,CORREO = @correo, CLAVE = @clave, ID_ROL = @id_rol, ESTADO = @estado WHERE @id_usuario= ID_USUARIO;
END;
Go

EXECUTE PA_EDITAR_USUARIO
@id = 3,
@nombres = 'Abraham',
@apellidos = 'Sapo',
@correo = 'sapoA@gmail.com',
@estado = 1;

Go 

CREATE PROC PA_ELIMINAR_USUARIO(
@id_usuario int
)
AS
BEGIN
   DELETE FROM USUARIO WHERE ID_USUARIO = @id_usuario
END;
GO 

CREATE TABLE AUTOR ( 
ID_AUTOR INT PRIMARY KEY IDENTITY,
NOMBRE NVARCHAR (50),
NACIONALIDAD NVARCHAR (50),
ESTADO BIT ,
FECHA_REGISTRO DATETIME DEFAULT GETDATE()
);
GO

INSERT INTO AUTOR (NOMBRE, NACIONALIDAD, ESTADO) VALUES('Gabriel García Márquez', 'Colombiana', 1),('Julio Verne', 'Francesa', 1),('Isabel Allende', 'Chilena', 1);
GO


CREATE PROC PA_LISTAR_AUTORES
AS
BEGIN 
    SELECT * FROM AUTOR;
END;

GO

CREATE PROCEDURE PA_BUSCAR_NOMBRE_AUTOR (
@nombre NVARCHAR(50)
)
AS
BEGIN
SELECT * FROM AUTOR WHERE NOMBRE = @nombre;
END;

EXECUTE PA_BUSCAR_NOMBRE
@nombre = 'Gisel';
GO

CREATE PROCEDURE PA_BUSCAR_AUTOR_ID (
@Id_Autor int
)
AS
BEGIN
SELECT * FROM AUTOR WHERE ID_AUTOR = @Id_Autor;
END;
GO
 CREATE PROC PA_REGISTRAR_AUTOR(
 @nombre NVARCHAR(50),
 @nacionalidad NVARCHAR(50),
 @estado BIT
 )
 AS
 BEGIN
 INSERT INTO AUTOR ( NOMBRE, NACIONALIDAD, ESTADO) Values ( @nombre, @nacionalidad , @estado );
 END;
 Go

 EXEC PA_REGISTRAR_AUTOR
 @nombre = 'Abraham',
 @nacionalidad = 'Ec',
 @estado = 1;

 GO

 CREATE PROC PA_EDITAR_AUTOR(
 @Id_Autor int,
 @nombre nvarchar(50),
 @nacionalidad nvarchar(50),
 @estado bit
 )
 AS
 BEGIN
     UPDATE AUTOR SET NOMBRE = @nombre, NACIONALIDAD = @nacionalidad, ESTADO = @estado WHERE ID_AUTOR = @Id_Autor
 END;

 GO

 CREATE PROC PA_ELIMINAR_AUTOR
 @Id_Autor int
 AS
 BEGIN 
    DELETE FROM AUTOR WHERE ID_AUTOR = @Id_Autor 
 END;
 GO

 EXEC PA_ELIMINAR_AUTOR 
GO

 CREATE TABLE GENERO(
 ID_GENERO INT PRIMARY KEY IDENTITY,
 NOMBRE NVARCHAR(50),
 ESTADO BIT,
 FECHA_REGISTRO DATETIME DEFAULT GETDATE()
 );
 GO

 INSERT INTO GENERO (NOMBRE, ESTADO) VALUES('Novela', 1),('Ciencia Ficción', 1),('Historia', 1);
GO

CREATE PROCEDURE PA_LISTAR_GENEROS
AS
BEGIN
    SELECT * FROM GENERO;
END;
GO

CREATE PROCEDURE PA_BUSCAR_NOMBRE_GENERO (
    @nombre NVARCHAR(50)
)
AS
BEGIN
    SELECT * FROM GENERO WHERE NOMBRE = @nombre;
END;
GO

CREATE PROCEDURE PA_BUSCAR_GENERO_ID (
    @Id_Genero INT
)
AS
BEGIN
    SELECT * FROM GENERO WHERE ID_GENERO = @Id_Genero;
END;
GO

CREATE PROCEDURE PA_REGISTRAR_GENERO (
    @nombre NVARCHAR(50),
    @estado BIT
)
AS
BEGIN
    INSERT INTO GENERO (NOMBRE, ESTADO) VALUES (@nombre, @estado);
END;
GO

CREATE PROCEDURE PA_EDITAR_GENERO (
    @Id_Genero INT,
    @nombre NVARCHAR(50),
    @estado BIT
)
AS
BEGIN
    UPDATE GENERO SET NOMBRE = @nombre, ESTADO = @estado WHERE ID_GENERO = @Id_Genero;
END;
GO

CREATE PROCEDURE PA_ELIMINAR_GENERO (
    @Id_Genero INT
)
AS
BEGIN
    DELETE FROM GENERO WHERE ID_GENERO = @Id_Genero;
END;
GO


 CREATE TABLE LIBRO (
ID_LIBRO INT PRIMARY KEY IDENTITY,
TITULO NVARCHAR(100),
ID_GENERO INT REFERENCES GENERO(ID_GENERO),
ID_AUTOR INT REFERENCES AUTOR (ID_AUTOR),
NUMERO_PAGINAS INT,
FECHA_PUBLICACION DATE, 
ESTADO BIT,
FECHA_REGISTRO DATETIME DEFAULT GETDATE()
);
GO

INSERT INTO LIBRO (TITULO, ID_GENERO, ID_AUTOR, NUMERO_PAGINAS, FECHA_PUBLICACION, ESTADO) VALUES
('Cien años de soledad', 1, 1, 471, '1967-05-30', 1),
('Viaje submarino', 2, 2, 384, '1870-01-01', 1),
('La casa de los espíritus', 1, 3, 433, '1982-01-01', 1);
GO

CREATE PROCEDURE PA_LISTAR_LIBROS
AS
BEGIN
    SELECT * FROM LIBRO;
END;
GO

CREATE PROCEDURE PA_BUSCAR_LIBRO_ID (
    @Id_Libro INT
)
AS
BEGIN
    SELECT * FROM LIBRO WHERE ID_LIBRO = @Id_Libro;
END;
GO

CREATE PROCEDURE PA_BUSCAR_TITULO_LIBRO (
    @titulo NVARCHAR(100)
)
AS
BEGIN
    SELECT * FROM LIBRO WHERE TITULO = @titulo;
END;
GO

CREATE PROCEDURE PA_REGISTRAR_LIBRO (
    @titulo NVARCHAR(100),
    @id_genero INT,
    @id_autor INT,
    @numero_paginas INT,
    @fecha_publicacion DATE,
    @estado BIT
)
AS
BEGIN
    INSERT INTO LIBRO (TITULO, ID_GENERO, ID_AUTOR, NUMERO_PAGINAS, FECHA_PUBLICACION, ESTADO)
    VALUES (@titulo, @id_genero, @id_autor, @numero_paginas, @fecha_publicacion, @estado);
END;
GO

CREATE PROCEDURE PA_EDITAR_LIBRO (
    @id_libro INT,
    @titulo NVARCHAR(100),
    @id_genero INT,
    @id_autor INT,
    @numero_paginas INT,
    @fecha_publicacion DATE,
    @estado BIT
)
AS
BEGIN
    UPDATE LIBRO SET TITULO = @titulo, ID_GENERO = @id_genero, ID_AUTOR = @id_autor,NUMERO_PAGINAS = @numero_paginas, 
	FECHA_PUBLICACION = @fecha_publicacion,ESTADO = @estado
    WHERE ID_LIBRO = @id_libro;
END;
GO

CREATE PROCEDURE PA_ELIMINAR_LIBRO (
    @Id_Libro INT
)
AS
BEGIN
    DELETE FROM LIBRO WHERE ID_LIBRO = @Id_Libro;
END;
GO

CREATE TABLE CLIENTE(
ID_CLIENTE INT PRIMARY KEY IDENTITY,
NOMBRES NVARCHAR(50),
APELLIDOS NVARCHAR(50),
CEDULA VARCHAR(10),
ESTADO BIT, 
FECHA_REGISTRO DATETIME DEFAULT GETDATE()
);
GO

INSERT INTO CLIENTE (NOMBRES, APELLIDOS, CEDULA, ESTADO) VALUES
('Carlos', 'Ramírez', '0954123654', 1),
('Lucía', 'Mendoza', '0912345678', 1),
('Andrés', 'Santos', '0987654321', 1);
GO


CREATE PROCEDURE PA_LISTAR_CLIENTES
AS
BEGIN
    SELECT * FROM CLIENTE;
END;
GO

CREATE PROCEDURE PA_BUSCAR_CLIENTE_ID (
    @Id_Cliente INT
)
AS
BEGIN
    SELECT * FROM CLIENTE WHERE ID_CLIENTE = @Id_Cliente;
END;
GO

CREATE PROCEDURE PA_BUSCAR_NOMBRE_CLIENTE (
    @nombres NVARCHAR(50)
)
AS
BEGIN
    SELECT * FROM CLIENTE WHERE NOMBRES = @nombres;
END;
GO

CREATE PROCEDURE PA_REGISTRAR_CLIENTE (
    @nombres NVARCHAR(50),
    @apellidos NVARCHAR(50),
    @cedula VARCHAR(10),
    @estado BIT
)
AS
BEGIN
    INSERT INTO CLIENTE (NOMBRES, APELLIDOS, CEDULA, ESTADO)
    VALUES (@nombres, @apellidos, @cedula, @estado);
END;
GO

CREATE PROCEDURE PA_EDITAR_CLIENTE (
    @id_cliente INT,
    @nombres NVARCHAR(50),
    @apellidos NVARCHAR(50),
    @cedula VARCHAR(10),
    @estado BIT
)
AS
BEGIN
    UPDATE CLIENTE
    SET NOMBRES = @nombres, APELLIDOS = @apellidos, CEDULA = @cedula, ESTADO = @estado WHERE ID_CLIENTE = @id_cliente;
END;
GO

CREATE PROCEDURE PA_ELIMINAR_CLIENTE (
    @id_cliente INT
)
AS
BEGIN
    DELETE FROM CLIENTE WHERE ID_CLIENTE = @id_cliente;
END;
GO

CREATE TABLE PRESTAMO (
ID_PRESTAMO INT PRIMARY KEY IDENTITY,
ID_CLIENTE INT REFERENCES CLIENTE (ID_CLIENTE),
ID_USUARIO INT REFERENCES USUARIO(ID_USUARIO),
ID_LIBRO INT REFERENCES LIBRO (ID_LIBRO),
FECHA_PRESTAMO DATE, 
FECHA_DEVOLUCION DATE, 
ESTADO BIT
);
GO
INSERT INTO PRESTAMO (ID_CLIENTE, ID_USUARIO, ID_LIBRO, FECHA_PRESTAMO, FECHA_DEVOLUCION, ESTADO) VALUES
(1, 5, 1, '2025-08-01', '2025-08-15', 1),
(2, 7, 2, '2025-08-05', '2025-08-20', 1);

GO
CREATE PROCEDURE PA_LISTAR_PRESTAMOS
AS
BEGIN
    SELECT * FROM PRESTAMO;
END;
GO

CREATE PROCEDURE PA_BUSCAR_PRESTAMO_ID (
    @Id_Prestamo INT
)
AS
BEGIN
    SELECT * FROM PRESTAMO WHERE ID_PRESTAMO = @Id_Prestamo;
END;
GO

CREATE PROCEDURE PA_REGISTRAR_PRESTAMO (
    @id_cliente INT,
    @id_usuario INT,
    @id_libro INT,
    @fecha_prestamo DATE,
    @fecha_devolucion DATE,
    @estado BIT
)
AS
BEGIN
    INSERT INTO PRESTAMO (ID_CLIENTE, ID_USUARIO, ID_LIBRO, FECHA_PRESTAMO, FECHA_DEVOLUCION, ESTADO)
    VALUES (@id_cliente, @id_usuario, @id_libro, @fecha_prestamo, @fecha_devolucion, @estado);
END;
GO

 --procedimientos con agrupaciones 
CREATE PROC PA_BUSCAR_LIBRO_PRESTAMO(
  @titulo nvarchar(100)
 )
 AS
 BEGIN 
     SELECT L.TITULO, C.NOMBRES, P.FECHA_PRESTAMO FROM LIBRO L 
	 INNER JOIN PRESTAMO P ON L.ID_LIBRO = P.ID_LIBRO 
	 INNER JOIN CLIENTE C ON P.ID_CLIENTE = C.ID_CLIENTE
	 WHERE TITULO = @titulo
	 GROUP BY L.TITULO, C.NOMBRES, P.FECHA_PRESTAMO
 END;
 GO


 CREATE PROC PA_BUSCAR_AUTOR_LIBRO(
 @nombre nvarchar(50)
 )
 AS
 BEGIN
     SELECT A.NOMBRE, L.TITULO FROM AUTOR A 
	 INNER JOIN LIBRO L ON A.ID_AUTOR = L.ID_AUTOR
	 WHERE NOMBRE = @nombre
	 GROUP BY A.NOMBRE, L.TITULO 
 END;
 GO


 CREATE PROC PA_BUSCAR_CLIENTE_LIBRO_PRESTAMO(
 @nombres nvarchar (50)
 )
 AS
 BEGIN
    SELECT C.NOMBRES, L.TITULO, A.NOMBRE, P.FECHA_PRESTAMO FROM LIBRO L
	INNER JOIN AUTOR A ON L.ID_AUTOR = A.ID_AUTOR
	INNER JOIN PRESTAMO P ON L.ID_LIBRO = P.ID_LIBRO
	INNER JOIN CLIENTE C ON P.ID_CLIENTE =  C.ID_CLIENTE 
	WHERE NOMBRES = @nombres
	GROUP BY  C.NOMBRES, L.TITULO, A.NOMBRE, P.FECHA_PRESTAMO
 END;
 GO

 EXEC sp_rename 'PA_BUSCAR_USUARIO_LIBRO_PRESTAMO', 'PA_BUSCAR_CLIENTE_LIBRO_PRESTAMO';

 GO

CREATE PROC PA_OBTENER_MENU(
 @id_usuario int
 )
 AS
 BEGIN
      SELECT M.ID_MENU, M.NOMBRE, M.URL_MENU, M.FECHA_REGISTRO FROM USUARIO U 
	  INNER JOIN ROL R ON U.ID_ROL = R.ID_ROL
	  INNER JOIN PERMISO P ON R.ID_ROL = P.ID_ROL
	  INNER JOIN MENU M ON P.ID_MENU = M.ID_MENU
	  WHERE U.ID_USUARIO = @id_usuario
 END;
 GO

EXEC PA_OBTENER_MENU
@id_usuario = 7 ;

--Cambiar nombre del procedimiento
EXEC sp_rename 'NombreAntiguo', 'NombreNuevo'

--COMANDO PARA ENTITY FRAMEWORK DATABASE FIRST
/*Scaffold-DbContext "Server= DESKTOP-TFVCTTI\SQLEXPRESS;Database=BIBLIOTECA;Trusted_Connection=True;TrustServerCertificate=True;" 
Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -Context DBContext -ContextDir Data -DataAnnotations -Force*/


--Paq para MVS entity framework 

/*  Microsoft.AspNetCore.Authentication.JwtBearer

    Microsoft.EntityFrameworkCore

    Microsoft.EntityFrameworkCore.Design

    Microsoft.EntityFrameworkCore.SqlServer

    Microsoft.EntityFrameworkCore.Tools*/